### ISSUE TITLE
Don't use empty string for redefined translatable terms

### ISSUE THREAD

**Issue by voronind** [OCA/odoo-pre-commit-hooks#100]
Odoo 15. In my module I redefine `crm` module translation. I want to translate `CRM` to `CRM`.

`po-pretty-format` replace it to empty string and my translation ignores. Can we check module name?

```
#. module: crm
#: model:ir.ui.menu,name:crm.crm_menu_root
#: model_terms:ir.ui.view,arch_db:crm.digest_digest_view_form
#: model_terms:ir.ui.view,arch_db:crm.res_config_settings_view_form
msgid "CRM"
msgstr "CRM"  --> ""
```

**Comment by voronind** [comment]
Module `crm` has shitty translation of `CRM` term in my language. I want keep original term (`CRM`). I created module `crm_translation` and add in i18n directory:
```
#. module: crm
#: something
msgid "CRM"
msgstr "CRM"
```

`po-pretty-format` hook replace `msgstr` to "" (empty string) and Odoo uses shitty translation from `crm` module.

**Comment by moylop260** [comment]
@voronind 

You have a good point

You need to redefine to original English term in order to overwrite the translated term

This static checker doesn't have context about this case since that it doesn't know the original module/file terms

So, you have diferent workaorund here since that it can not be fixed

1) Fix the wrong translated term from weblate
2) Disable "autofix" option for this checker in your configuration files
3) Discard this special file for this checker in your configuration files

**Comment by luisg123v** [comment]
Hi @moylop260,

Thinking it better, maybe removing an existing translation is a valid case, as long as it's under the directory `i18n_extra`.

The reason for clearing translated terms is to generate a file as similar as possible to the one exported by Odoo, and to mimic the behavior (if the term is from our module, there's no need to fill the translation, because result will be the same). But since when dealing with manual translations (`i18n_extra`) terms will be from other modules, leaving the term empty and fill it with the same string as the original term will have different behaviors. Actually, it wouldn't make much of a sense to include a term in the `i18n_extra` directory and leave translation empty, because it will be ignored.

What do you think?

Regards,

**Comment by moylop260** [comment]
@luisg123v 

Who should take care about excluding files, [the hooks itself](https://github.com/OCA/odoo-pre-commit-hooks) or the [pre-commit configuration file](https://github.com/OCA/oca-addons-repo-template/blob/f8cceacfd7c6594223087f0b3d67adcedaefb8be/src/.pre-commit-config.yaml.jinja#L137-L141)?

**Comment by luisg123v** [comment]
@moylop260 I think the file shouldn't be excluded, it just should change its behavior depending on if it's under `i18n` or `i18n_extra`:
- If under `i18n`, same translation should be cleared.
- If under `i18n_extra`, same translation should be allowed, and empty translations should be filled (the opposite as the above).

**Comment by moylop260** [comment]
@voronind 

In this case, are you using a i18n_extra/*.po file?

**Comment by voronind** [comment]
I am using i18n/. I dont know difference between them

пт, 26 июл. 2024 г., 07:36 moylop260 ***@***.***>:

**Comment by luisg123v** [comment]
@voronind `i18n` is for translations that belong to your own module, while `i18n_extra` is intended to modify translations from other modules.

**Comment by yajo** [comment]
I have a different use case.

We have `l10n_es` installed. This module writes original terms in Spanish ([one example](https://github.com/odoo/odoo/blob/793b384d7792a171ee483d88ce1a69c21dd925f2/addons/l10n_es/data/account_tax_data.xml#L684)).

Then we have foreign customers. We want to translate some terms into English for them.

However, for Odoo, the source term is always `en_US` (even if it is `es_ES` in reality). Thus, to fix that, we need:
- `i18n_extra/en.po`, translating those Spanish terms into English.
- `i18n_extra/es.po`, **repeating Spanish terms into Spanish**. Otherwise Spanish terms would be written in English (because English is for odoo the original term, and we're overriding it). **If these terms are emptied instead of repeated, it fails**.

So, I agree with https://github.com/OCA/odoo-pre-commit-hooks/issues/100#issuecomment-2251880678. I think that's the solution.

**Comment by moylop260** [comment]
Thank you to all for feedback

Somebody could help us to fix it, please?

I mean, creating PR
