### ISSUE TITLE
Run on modified files only

### ISSUE THREAD

**Issue by sbidoul** [OCA/odoo-pre-commit-hooks#11]
By default, pre-commit passes modified files to the hooks.

This project's hook has 

```
types: [python]
files: /\_\_(manifest|openerp)\_\_\.py$
```

So it will trigger only on addon manifests? Or it should be configured with `always_run: true`?

Could it be possible to run the hook on modified files only? For instance, there is no need to check all .po files if they have not been modified.

That could be important for performance, especially when running locally.

**Comment by moylop260** [comment]
Good question!

Thank you!

I think `always_run: true` is good for data/demo manifest section.

A few checks needs to be evaluated with the whole Odoo module

The first version was using the xml files but it needs a way to get all the xmlids of all the files not only the changed one

Even, I have improvement the performance re-using the XML nodes compared with pylint

So, I have decided to change it to evaluate the whole module because you can add a new data file in the manifest but without changing the xml itself and it needs to be evaluated too

Similar case for CSV files

However, you have a good point for .po files since we don't have this case of use for these kind of files

Let me check how we can create a separated hook only for po files...

Thank for the issue

**Comment by sbidoul** [comment]
I'm wondering if there are standard hooks for .po files. After all our check are not really Odoo-specific.

**Comment by moylop260** [comment]
You are right!

I feel the same

It could be great!

**Comment by moylop260** [comment]
For record, the option `always_run: true`  is not working as we thought:
 - <img width="1207" alt="Screen Shot 2022-10-18 at 12 23 00" src="https://user-images.githubusercontent.com/6644187/196501334-7108683d-620b-4aad-91ea-daeb1b127a1a.png">


This option is related with unmatched files

So, we will need to consider all the odoo module extension files as xml, csv, manifest files in order to group by module and run only one time the checks over the modules...
