### ISSUE TITLE
Add column number to xml checks

### ISSUE THREAD

**Issue by moylop260** [OCA/odoo-pre-commit-hooks#64]
lxml supports `xml_node.sourceline` but what about column number?

R&D - Check if it is possible to add it

**Comment by antonag32** [comment]
I looked around the entire documentation, google and mailing list for LXML. Column number sometimes appear on exceptions but apparently there is no API to access it so I think we should close this for now, it seems like it is not possible (easily).

Subclassing the XML parser to access internals is also not as straightforward since it is all Cython,
