### ISSUE TITLE
manifest-syntax-error: false negative on appropriate syntax

### ISSUE THREAD

**Issue by yajo** [OCA/odoo-pre-commit-hooks#91]
In https://github.com/OCA/project/actions/runs/6706164306/job/18222107113, which corresponds to 1st commit of https://github.com/OCA/project/pull/1187, you can see this failure:

```
****manifest-syntax-error****
project_stage_closed/__manifest__.py:1 could not be loaded - [manifest-syntax-error]
```

[See here](https://github.com/OCA/project/pull/1187/files#diff-4eae095fac0293a1c35d937d3f1ac335c51710b1071cb11bf00277013ae170e1) the code that was being detected as a syntax error and the diff applied to fix that.

It is an obvious false negative because the syntax is correct Python code. Indeed it was ugly, but if that's what it was really checking, then the error should be "ugly code", not "syntax error".

**Comment by moylop260** [comment]
@antonag32 I think it is related to support comments

Could you check how odoo is processing this file, please?

https://github.com/odoo/odoo/blob/0067c081b6e4a7a02d170303210067433bb14c89/odoo/modules/module.py#L337

Check the output is good using: `ast.literal_eval(pycompat.to_text(f.read()))`

```python
{'name': 'Project Task Stage Closed',
 'summary': 'Project Task Stage Closed',
 'author': 'ACSONE SA/NV,Tecnativa,Odoo Community Association (OCA)',
 'website': 'https://github.com/OCA/project',
 'category': 'Project Management',
 'version': '14.0.2.0.0',
 'license': 'AGPL-3',
 'depends': ['project'],
 'data': []}
```

**Comment by moylop260** [comment]
@yajo 

Sorry for delay

The issue was the odoo module didn't have `__init__.py` file

You can double-confirm using the same sha raising error:
 - https://github.com/oca/project/tree/45b08960bec9980d0217aba3482819a7a5ef048a/project_stage_closed
  - <img width="739" alt="Screenshot 2024-03-27 at 12 26 13 p m" src="https://github.com/OCA/odoo-pre-commit-hooks/assets/6644187/e8bdad5b-f0e8-437c-bd8e-9d99b21657cf">


So, the lint raises the following whole message:

```bash
~/odoo/project (45b08960b)
$ oca-checks-odoo-module project_stage_closed

The path /Users/moylop260/odoo/project/project_stage_closed/__manifest__.py does not have __init__.py file

****manifest-syntax-error****
project_stage_closed/__manifest__.py:1 could not be loaded - [manifest-syntax-error]
```

But your latest commit has the `__init__.py` file:
 - https://github.com/moduon/project/tree/a18666cc3bcc9e251e91b82533724b3ee45d1c65/project_stage_closed

Maybe the message should be a little different but it is a different matter

Regards!
